name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          CODE_LANG: typescript
          LANG_COUNT: 10 
          SHOW_TIME: true 
          SHOW_TOTAL: true 
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true 
